- hostname: "{{switches['CampusA-Spine1']['hostname']}}"
  serial: "{{switches['CampusA-Spine1']['serial']}}"
  model: "vEOS-lab"
- hostname: "{{switches['CampusA-Spine2']['hostname']}}"
  serial: "{{switches['CampusA-Spine2']['serial']}}"
  model: "vEOS-lab"
- hostname: "{{switches['CampusA-Leaf1A']['hostname']}}"
  serial: "{{switches['CampusA-Leaf1A']['serial']}}"
  model: "vEOS-lab"
- hostname: "{{switches['CampusA-Leaf1B']['hostname']}}"
  serial: "{{switches['CampusA-Leaf1B']['serial']}}"
  model: "vEOS-lab"
- hostname: "{{switches['CampusA-Leaf1C']['hostname']}}"
  serial: "{{switches['CampusA-Leaf1C']['serial']}}"
  model: "vEOS-lab"
- hostname: "{{switches['CampusA-Leaf2A']['hostname']}}"
  serial: "{{switches['CampusA-Leaf2A']['serial']}}"
  model: "vEOS-lab"
