- hostname: "{CampusA-Spine1_Hostname}"
  serial: "{CampusA-Spine1_Serial}"
  model: "vEOS-lab"
- hostname: "{CampusA-Spine2_Hostname}"
  serial: "{CampusA-Spine2_Serial}"
  model: "vEOS-lab"
- hostname: "{CampusA-Leaf1A_Hostname}"
  serial: "{CampusA-Leaf1A_Serial}"
  model: "vEOS-lab"
- hostname: "{CampusA-Leaf1B_Hostname}"
  serial: "{CampusA-Leaf1B_Serial}"
  model: "vEOS-lab"
- hostname: "{CampusA-Leaf1C_Hostname}"
  serial: "{CampusA-Leaf1C_Serial}"
  model: "vEOS-lab"
- hostname: "{CampusA-Leaf2A_Hostname}"
  serial: "{CampusA-Leaf2A_Serial}"
  model: "vEOS-lab"
