- hostname: "{{switches['CampusA-Spine1'].hostname}}"
  serial: "{{switches['CampusA-Spine1'].sn}}"
  model: "vEOS-lab"
- hostname: "{{switches['CampusA-Spine2'].hostname}}"
  serial: "{{switches['CampusA-Spine2'].sn}}"
  model: "vEOS-lab"
- hostname: "{{switches['CampusA-Leaf1A'].hostname}}"
  serial: "{{switches['CampusA-Leaf1A'].sn}}"
  model: "vEOS-lab"
- hostname: "{{switches['CampusA-Leaf1B'].hostname}}"
  serial: "{{switches['CampusA-Leaf1B'].sn}}"
  model: "vEOS-lab"
- hostname: "{{switches['CampusA-Leaf1C'].hostname}}"
  serial: "{{switches['CampusA-Leaf1C'].sn}}"
  model: "vEOS-lab"
- hostname: "{{switches['CampusA-Leaf2A'].hostname}}"
  serial: "{{switches['CampusA-Leaf2A'].sn}}"
  model: "vEOS-lab"
- hostname: "{{switches['CampusB-Spine1'].hostname}}"
  serial: "{{switches['CampusB-Spine1'].sn}}"
  model: "vEOS-lab"
- hostname: "{{switches['CampusB-Spine2'].hostname}}"
  serial: "{{switches['CampusB-Spine2'].sn}}"
  model: "vEOS-lab"
- hostname: "{{switches['CampusB-Leaf1A'].hostname}}"
  serial: "{{switches['CampusB-Leaf1A'].sn}}"
  model: "vEOS-lab"
- hostname: "{{switches['CampusB-Leaf1B'].hostname}}"
  serial: "{{switches['CampusB-Leaf1B'].sn}}"
  model: "vEOS-lab"
- hostname: "{{switches['CampusB-Leaf1C'].hostname}}"
  serial: "{{switches['CampusB-Leaf1C'].sn}}"
  model: "vEOS-lab"
- hostname: "{{switches['CampusB-Leaf2A'].hostname}}"
  serial: "{{switches['CampusB-ZTR'].sn}}"
  model: "vEOS-lab"
