configlets:
  - name: "allUsers"
    filename: "allUsers.j2"
  - name: "mgmt_Leaf1a"
    filename: "mgmt_Leaf1a.j2"
  - name: "mgmt_Leaf1b"
    filename: "mgmt_Leaf1b.j2"
  - name: "mgmt_Leaf1c"
    filename: "mgmt_Leaf1c.j2"
  - name: "mgmt_Leaf2a"
    filename: "mgmt_Leaf2a.j2"
  - name: "mgmt_Spine1"
    filename: "mgmt_Spine1.j2"
  - name: "mgmt_Spine2"
    filename: "mgmt_Spine2.j2"
  - name: "CampusA_Base"
    filename: "CampusA_Base.j2"
