configlets:
  - name: "allUsers"
    filename: "allUsers.txt"
  - name: "mgmt_Leaf1a"
    filename: "mgmt_Leaf1a.txt"
  - name: "mgmt_Leaf1b"
    filename: "mgmt_Leaf1b.txt"
  - name: "mgmt_Leaf1c"
    filename: "mgmt_Leaf1c.txt"
  - name: "mgmt_Leaf2a"
    filename: "mgmt_Leaf2a.txt"
  - name: "mgmt_Spine1"
    filename: "mgmt_Spine1.txt"
  - name: "mgmt_Spine2"
    filename: "mgmt_Spine2.txt"
  - name: "CampusA_Base"
    filename: "CampusA_Base.txt"
