studios:
  - name: CampusL2L3EVPN
    id: studio-avd-campus-fabric
    filename: campus.j2
  - name: DateTime
    id: studio-date-time
    filename: date_time.j2
  - name: StreamingTelemetry
    id: studio-telemetry-config
    selector: "device: *"
