configlets:
  - name: "allUsers"
    filename: "allUsers.txt"
  - name: "mgmt_Leaf1a"
    filename: "mgmt_Leaf1a.txt"
  - name: "mgmt_Leaf1b"
    filename: "mgmt_Leaf1b.txt"
  - name: "mgmt_Leaf1c"
    filename: "mgmt_Leaf1c.txt"
  - name: "mgmt_Leaf2a"
    filename: "mgmt_Leaf2a.txt"
  - name: "mgmt_Spine1"
    filename: "mgmt_Spine1.txt"
  - name: "mgmt_Spine2"
    filename: "mgmt_Spine2.txt"
  - name: "CampusA_Base"
    filename: "CampusA_Base.txt"

assignments:
  #################
  - container: "Leaf1A_A"
    configlets: [ "mgmt_Leaf1a" ]
    query: "device: {CampusA-Leaf1A_Serial}"
  - container: "Leaf1B_A"
    configlets: [ "mgmt_Leaf1b" ]
    query: "device: {CampusA-Leaf1B_Serial}"
  - container: "Leaf1C_A"
    configlets: [ "mgmt_Leaf1c" ]
    query: "device: {CampusA-Leaf1C_Serial}"
  - container: "Leaf2A_A"
    configlets: [ "mgmt_Leaf2a" ]
    query: "device: {CampusA-Leaf2A_Serial}"
  - container: "Spine1_A"
    configlets: [ "mgmt_Spine1" ]
    query: "device: {CampusA-Spine1_Serial}"
  - container: "Spine2_A"
    configlets: [ "mgmt_Spine2" ]
    query: "device: {CampusA-Spine2_Serial}"
  
 ########
  - container: "Leaf2"
    query: "Workshop: Leaf2"
    children: [ "Leaf2A_A" ]

  - container: "Leaf1-Member-Leaf"
    query: "Workshop: Leaf1-Member-Leaf"
    children: [ "Leaf1C_A" ]
  - container: "Leaf1"
    query: "Workshop: Leaf1"
    children: [ "Leaf1-Member-Leaf", "Leaf1A_A", "Leaf1B_A" ]

  ######  
  - container: "Leaf"
    query: "Workshop: Leaf"
    children: [ "Leaf1", "Leaf2" ]

  ######  
  - container: "Spine"
    query: "Workshop: Spine"
    children: [ "Spine1_A", "Spine2_A" ]

  ######  
  - container: "CampusA"
    query: "Workshop: CampusA"
    configlets: [ "CampusA_Base" ]
    children: [ "Spine", "Leaf" ]

  - container: "Base"
    query: "device: *"
    configlets: [ "allUsers" ]
    children: [ "CampusA" ]
    isRoot: true

