tags:
  - key: Workshop
    values: [ CampusA, Leaf, Leaf1, Leaf1-Member-Leaf, Leaf2, Spine ]
  - key: Campus
    values: [ Workshop ]
  - key: Campus-Pod
    values: [ CampusA ]
  - key: Access-Pod
    values: [ Pod1, Pod2 ]
  - key: Role
    values: [ Leaf, Member-Leaf, Spine ]
assignments:
    - key: Workshop
      value: CampusA
      devices: [ "{{switches['CampusA-Spine1']['serial']}}", "{{switches['CampusA-Spine2']['serial']}}", "{{switches['CampusA-Leaf1A']['serial']}}", "{{switches['CampusA-Leaf1B']['serial']}}", "{{switches['CampusA-Leaf1C']['serial']}}", "{{switches['CampusA-Leaf2A']['serial']}}" ]
    - key: Workshop
      value: Spine
      devices: [ "{{switches['CampusA-Spine1']['serial']}}", "{{switches['CampusA-Spine2']['serial']}}" ]
    - key: Workshop
      value: Leaf
      devices: [ "{{switches['CampusA-Leaf1A']['serial']}}", "{{switches['CampusA-Leaf1B']['serial']}}", "{{switches['CampusA-Leaf1C']['serial']}}", "{{switches['CampusA-Leaf2A']['serial']}}" ]
    - key: Workshop
      value: Leaf1
      devices: [ "{{switches['CampusA-Leaf1A']['serial']}}", "{{switches['CampusA-Leaf1B']['serial']}}", "{{switches['CampusA-Leaf1C']['serial']}}" ]
    - key: Workshop
      value: Leaf1-Member-Leaf
      devices: [ "{{switches['CampusA-Leaf1C']['serial']}}" ]
    - key: Workshop
      value: Leaf2
      devices: [ "{{switches['CampusA-Leaf2A']['serial']}}" ]
    - key: Campus
      value: Workshop
      devices: [ "{{switches['CampusA-Spine1']['serial']}}", "{{switches['CampusA-Spine2']['serial']}}", "{{switches['CampusA-Leaf1A']['serial']}}", "{{switches['CampusA-Leaf1B']['serial']}}", "{{switches['CampusA-Leaf1C']['serial']}}", "{{switches['CampusA-Leaf2A']['serial']}}" ]
    - key: Campus-Pod
      value: CampusA
      devices: [ "{{switches['CampusA-Spine1']['serial']}}", "{{switches['CampusA-Spine2']['serial']}}", "{{switches['CampusA-Leaf1A']['serial']}}", "{{switches['CampusA-Leaf1B']['serial']}}", "{{switches['CampusA-Leaf1C']['serial']}}", "{{switches['CampusA-Leaf2A']['serial']}}" ]
    - key: Access-Pod
      value: Pod1
      devices: [ "{{switches['CampusA-Leaf1A']['serial']}}", "{{switches['CampusA-Leaf1B']['serial']}}", "{{switches['CampusA-Leaf1C']['serial']}}" ]
    - key: Access-Pod
      value: Pod2
      devices: [ "{{switches['CampusA-Leaf2A']['serial']}}" ]
    - key: Role
      value: Leaf
      devices: [ "{{switches['CampusA-Leaf1A']['serial']}}", "{{switches['CampusA-Leaf1B']['serial']}}", "{{switches['CampusA-Leaf2A']['serial']}}" ]
    - key: Role
      value: Member-Leaf
      devices: [ "{{switches['CampusA-Leaf1C']['serial']}}" ]
    - key: Role
      value: Spine
      devices: [ "{{switches['CampusA-Spine1']['serial']}}", "{{switches['CampusA-Spine2']['serial']}}" ]

