tags:
  - key: Workshop
    values: [ CampusA, Leaf, Leaf1, Leaf1-Member-Leaf, Leaf2, Spine ]
  - key: Campus
    values: [ Workshop ]
  - key: Campus-Pod
    values: [ CampusA ]
  - key: Access-Pod
    values: [ Pod1, Pod2 ]
  - key: Role
    values: [ Leaf, Member-Leaf, Spine ]
assignments:
    - key: Workshop
      value: CampusA
      devices: [ "{CampusA-Spine1_Serial}", "{CampusA-Spine2_Serial}", "{CampusA-Leaf1A_Serial}", "{CampusA-Leaf1B_Serial}", "{CampusA-Leaf1C_Serial}", "{CampusA-Leaf2A_Serial}" ]
    - key: Workshop
      value: Spine
      devices: [ "{CampusA-Spine1_Serial}", "{CampusA-Spine2_Serial}" ]
    - key: Workshop
      value: Leaf
      devices: [ "{CampusA-Leaf1A_Serial}", "{CampusA-Leaf1B_Serial}", "{CampusA-Leaf1C_Serial}", "{CampusA-Leaf2A_Serial}" ]
    - key: Workshop
      value: Leaf1
      devices: [ "{CampusA-Leaf1A_Serial}", "{CampusA-Leaf1B_Serial}", "{CampusA-Leaf1C_Serial}" ]
    - key: Workshop
      value: Leaf1-Member-Leaf
      devices: [ "{CampusA-Leaf1C_Serial}" ]
    - key: Workshop
      value: Leaf2
      devices: [ "{CampusA-Leaf2A_Serial}" ]
    - key: Campus
      value: Workshop
      devices: [ "{CampusA-Spine1_Serial}", "{CampusA-Spine2_Serial}", "{CampusA-Leaf1A_Serial}", "{CampusA-Leaf1B_Serial}", "{CampusA-Leaf1C_Serial}", "{CampusA-Leaf2A_Serial}" ]
    - key: Campus-Pod
      value: CampusA
      devices: [ "{CampusA-Spine1_Serial}", "{CampusA-Spine2_Serial}", "{CampusA-Leaf1A_Serial}", "{CampusA-Leaf1B_Serial}", "{CampusA-Leaf1C_Serial}", "{CampusA-Leaf2A_Serial}" ]
    - key: Access-Pod
      value: Pod1
      devices: [ "{CampusA-Leaf1A_Serial}", "{CampusA-Leaf1B_Serial}", "{CampusA-Leaf1C_Serial}" ]
    - key: Access-Pod
      value: Pod2
      devices: [ "{CampusA-Leaf2A_Serial}" ]
    - key: Role
      value: Leaf
      devices: [ "{CampusA-Leaf1A_Serial}", "{CampusA-Leaf1B_Serial}", "{CampusA-Leaf2A_Serial}" ]
    - key: Role
      value: Member-Leaf
      devices: [ "{CampusA-Leaf1C_Serial}" ]
    - key: Role
      value: Spine
      devices: [ "{CampusA-Spine1_Serial}", "{CampusA-Spine2_Serial}" ]

